# Convert the provided list of course strings into structured dicts with title and description
raw_courses = [
    "Bachelor of Science in Computer Science: Algorithms, programming, AI, and systems software.",
    "Bachelor of Science in Information Technology: IT infrastructure, networking, databases, and cybersecurity.",
    "Bachelor of Science in Information Systems: Business technology integration, systems analysis, and data management.",
    "Bachelor of Science in Software Engineering: Software lifecycle, development, QA, and project management.",
    "Bachelor of Science in Data Science: Data analysis, statistics, machine learning, and visualization.",
    "Bachelor of Science in Cybersecurity: Threat analysis, digital forensics, and security protocols.",
    "Bachelor of Science in Artificial Intelligence: Deep learning, NLP, robotics, and AI ethics.",
    "Bachelor of Science in Game Development: Game design, graphics programming, and physics engines.",
    "Bachelor of Science in Robotics: Automation, mechatronics, embedded systems, and AI integration.",
    "Bachelor of Science in Human-Computer Interaction: Usability, UI/UX design, and cognitive ergonomics.",
    "Bachelor of Science in Cloud Computing: Distributed systems, cloud services, and virtualization.",
    "Bachelor of Science in Blockchain and Financial Technology: Cryptocurrency systems, smart contracts, and fintech innovation.",
    "Bachelor of Science in Electrical Engineering: Circuits, electromagnetism, signal systems.",
    "Bachelor of Science in Electronics Engineering: Semiconductor devices, embedded systems, and communications.",
    "Bachelor of Science in Mechanical Engineering: Kinematics, thermal systems, and robotics.",
    "Bachelor of Science in Civil Engineering: Construction, structures, transportation, and geotechnics.",
    "Bachelor of Science in Architecture: Structural design, architectural theory, and urban design.",
    "Bachelor of Science in Chemical Engineering: Industrial chemistry, plant design, and process simulation.",
    "Bachelor of Science in Biomedical Engineering: Biomechanics, biosensors, and medical imaging.",
    "Bachelor of Science in Aerospace Engineering: Aircraft design, aerodynamics, and propulsion systems.",
    "Bachelor of Science in Environmental Engineering: Waste treatment, environmental planning, and sustainability.",
    "Bachelor of Science in Marine Engineering: Ship propulsion systems, thermodynamics, and marine maintenance.",
    "Bachelor of Science in Biology: Cell biology, ecology, genetics, and molecular biology.",
    "Bachelor of Science in Marine Biology: Aquatic ecosystems, marine biodiversity, and conservation.",
    "Bachelor of Science in Physics: Mechanics, quantum theory, and electromagnetism.",
    "Bachelor of Science in Chemistry: Organic, inorganic, physical, and analytical chemistry.",
    "Bachelor of Science in Mathematics: Calculus, algebra, statistics, and mathematical modeling.",
    "Bachelor of Science in Statistics: Data analysis, sampling theory, and statistical computing.",
    "Bachelor of Science in Environmental Science: Ecology, environmental policy, and resource management.",
    "Bachelor of Science in Genetic Engineering: Gene editing, molecular genetics, and biotechnology.",
    "Bachelor of Science in Cognitive Science: Neuroscience, psychology, AI, and linguistics.",
    "Bachelor of Science in Nursing: Clinical care, patient safety, and pharmacology.",
    "Bachelor of Science in Public Health: Epidemiology, global health, and health policy.",
    "Bachelor of Science in Health Sciences: Healthcare systems, clinical foundations, and wellness promotion.",
    "Bachelor of Science in Physical Therapy: Biomechanics, rehabilitation, and physical assessment.",
    "Bachelor of Science in Occupational Therapy: Functional training and therapy planning.",
    "Bachelor of Science in Medical Technology: Laboratory diagnostics, microbiology, and hematology.",
    "Bachelor of Science in Nutrition and Dietetics: Metabolism, clinical nutrition, and food science.",
    "Bachelor of Science in Pharmacy: Drug chemistry, therapeutics, and pharmaceutical law.",
    "Bachelor of Science in Radiologic Technology: Imaging physics, radiography, and radiologic safety.",
    "Bachelor of Science in Respiratory Therapy: Pulmonary care, ventilator management, and cardiopulmonary diagnostics.",
    "Bachelor of Science in Midwifery: Maternal and child health, prenatal care, and labor management.",
    "Bachelor of Science in Dental Technology: Dental materials, prosthodontics, and oral anatomy.",
    "Bachelor of Science in Medical Laboratory Science: Clinical diagnostics, pathology, and quality assurance.",
    "Bachelor of Science in Disaster Risk Management: Emergency response, risk reduction, and public health preparedness.",
    "Bachelor of Science in Business Administration: Finance, marketing, operations, and entrepreneurship.",
    "Bachelor of Science in Finance: Investment analysis, corporate finance, and financial planning.",
    "Bachelor of Science in Accounting: Auditing, taxation, cost accounting, and financial reporting.",
    "Bachelor of Science in Marketing: Branding, digital strategy, consumer behavior, and analytics.",
    "Bachelor of Science in Entrepreneurship: Startups, innovation, and venture capital management.",
    "Bachelor of Science in Business Analytics: Predictive modeling, dashboarding, and KPI evaluation.",
    "Bachelor of Science in E-Commerce: Online business, payment systems, and digital logistics.",
    "Bachelor of Science in Real Estate Management: Property valuation, brokerage, and land use laws.",
    "Bachelor of Science in Supply Chain Management: Logistics, procurement, inventory, and distribution.",
    "Bachelor of Science in Hospitality Management: Hotel and restaurant operations, service management.",
    "Bachelor of Science in Tourism Management: Tour operations, travel planning, and destination marketing.",
    "Bachelor of Science in Aviation: Flight operations, aeronautics, and air traffic regulations.",
    "Bachelor of Science in Marine Transportation: Seamanship, navigation, and maritime safety.",
    "Bachelor of Science in Cruise Line Operations: Onboard services, hospitality, and maritime tourism.",
    "Bachelor of Science in Culinary Arts Management: Kitchen operations, nutrition, and food service leadership.",
    "Bachelor of Education: Educational theory, curriculum design, and pedagogical techniques.",
    "Bachelor of Arts in Psychology: Behavioral science, developmental, clinical, and cognitive psychology.",
    "Bachelor of Social Work: Community service, social justice, counseling, and casework.",
    "Bachelor of Arts in Sociology: Social systems, deviance, and cultural change.",
    "Bachelor of Arts in Anthropology: Human evolution, ethnography, and sociocultural analysis.",
    "Bachelor of Arts in Political Science: Governance, policy-making, political theory, and diplomacy.",
    "Bachelor of Arts in Public Administration: Bureaucracy, policy formulation, and organizational theory.",
    "Bachelor of Science in Legal Management: Legal principles, corporate law, and business governance.",
    "Bachelor of Science in Paralegal Studies: Legal writing, litigation support, and case preparation.",
    "Bachelor of Arts in International Relations: Diplomacy, conflict resolution, and foreign policy.",
    "Bachelor of Arts in Development Studies: Poverty alleviation, NGOs, and sustainable development.",
    "Bachelor of Arts in Gender Studies: Gender theory, equality movements, and intersectionality.",
]

# Split and convert into structured course objects
structured_courses = [
    {"title": course.split(":")[0].strip(), "description": course.split(":")[1].strip()}
    for course in raw_courses if ":" in course
]

print(structured_courses)  # show first 5 entries for inspection
